"""add_foreignkey_messages_table

Revision ID: 02494cf5a198
Revises: 7774be7b6b57
Create Date: 2026-07-20 20:48:07.419279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02494cf5a198'
down_revision: Union[str, Sequence[str], None] = '7774be7b6b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               postgresql_using='conversation_id::uuid',
               existing_nullable=False)
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
