"""rename owner_id to user_id and make page_number nullable

Revision ID: 2cbecc27cd20
Revises: 96e889b47b83
Create Date: 2026-07-15 15:12:25.886858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbecc27cd20'
down_revision: Union[str, Sequence[str], None] = '96e889b47b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.add_column('conversations', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('conversations', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.add_column('conversations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_conversations_owner_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_column('conversations', 'owner_id')
    op.add_column('document_chunks', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('document_chunks', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.add_column('document_chunks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('document_chunks', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('documents', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('documents', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_column('documents', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('owner_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'deleted_by')
    op.drop_column('documents', 'is_deleted')
    op.drop_column('documents', 'user_id')
    op.alter_column('document_chunks', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('document_chunks', 'deleted_at')
    op.drop_column('document_chunks', 'deleted_by')
    op.drop_column('document_chunks', 'is_deleted')
    op.add_column('conversations', sa.Column('owner_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_owner_id'), 'conversations', ['owner_id'], unique=False)
    op.drop_column('conversations', 'deleted_at')
    op.drop_column('conversations', 'deleted_by')
    op.drop_column('conversations', 'is_deleted')
    op.drop_column('conversations', 'user_id')
    # ### end Alembic commands ###
