"""update documents table

Revision ID: 91a248aed7a2
Revises: 8384afb5584d
Create Date: 2026-07-09 11:15:59.970453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a248aed7a2'
down_revision: Union[str, Sequence[str], None] = '8384afb5584d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_provider', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'storage_provider')
    # ### end Alembic commands ###
